version: '3.8'
services:
  db:
    logging:
      driver: "none"
    image: ${DB_IMAGE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
  rust_server:
    network_mode: host
    build:
      context: .
      dockerfile: rust_server/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - db
    environment:
      - DB_HOST=db # used to be cassandra, might cause bugs
      - DB_PORT=${DB_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3