version: '3.8'

networks:
  common:
    driver: bridge

services:
  db:
    image: ${DB_IMAGE}
    command: ["--listen-address=127.0.0.1", "--rpc-address=127.0.0.1", "--broadcast-rpc-address=127.0.0.1"]
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - common
      
  rust_server:
    image: helloredwing/vector:latest
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4    
    ports:
      - "50051:50051"
    depends_on:
      - db
    networks:
      - common

  network_test:
    image: busybox
    command: ping -c 2 142.250.186.142
    networks:
      - common
