version: '3.8'

networks:
  common:
    driver: bridge

services:
  db:
    image: ${DB_IMAGE}
    command: ["--smp 1", "--memory 750M", "--overprovisioned 1"] #"--listen-address=0.0.0.0", "--rpc-address=0.0.0.0", "--broadcast-rpc-address=127.0.0.1", 
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - common
      
  rust_server:
    image: helloredwing/vector:latest
    env_file:
      - .env # configure here for dev/stage/prod here and in the provisioner remote-exec of redwing-os/terraform
    dns:
      - 8.8.8.8
      - 8.8.4.4    
    ports:
      - "50051:50051"
    depends_on:
      - db
    networks:
      - common

  network_test:
    image: busybox
    command: ping -c 2 142.250.186.142
    networks:
      - common