version: '3.8'

networks:
  common:
    driver: bridge

services:
  db:
    image: ${DB_IMAGE}
    command: ${DB_STARTUP_CMD}
    ports:
      - "9042:9042"
    networks:
      - common
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 30s
      timeout: 10s
      retries: 5

  rust_server:
    image: helloredwing/vector:latest
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4    
    ports:
      - "50051:50051"
    depends_on:
      - db
    networks:
      - common

  catalyst:
    image: helloredwing/catalyst:latest
    networks:
      - common

  network_test:
    image: busybox
    command: ping -c 2 142.250.186.142
    networks:
      - common