# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectordb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evectordb.proto\x12\x08vectordb\"1\n\x12VectorWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\"H\n\x17VectorBatchWriteRequest\x12-\n\x07vectors\x18\x01 \x03(\x0b\x32\x1c.vectordb.VectorWriteRequest\"&\n\x13VectorWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\x11VectorReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"3\n\x12VectorReadResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"2\n\x13VectorUpdateRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\"\'\n\x14VectorUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x13VectorDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\'\n\x14VectorDeleteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"S\n\x1aVectorEmbedAndWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\x12\x0c\n\x04rows\x18\x03 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x04 \x01(\x05\x32\xcb\x03\n\x08VectorDB\x12N\n\nBatchWrite\x12!.vectordb.VectorBatchWriteRequest\x1a\x1d.vectordb.VectorWriteResponse\x12\x44\n\x05Write\x12\x1c.vectordb.VectorWriteRequest\x1a\x1d.vectordb.VectorWriteResponse\x12\x41\n\x04Read\x12\x1b.vectordb.VectorReadRequest\x1a\x1c.vectordb.VectorReadResponse\x12G\n\x06Update\x12\x1d.vectordb.VectorUpdateRequest\x1a\x1e.vectordb.VectorUpdateResponse\x12G\n\x06\x44\x65lete\x12\x1d.vectordb.VectorDeleteRequest\x1a\x1e.vectordb.VectorDeleteResponse\x12T\n\rEmbedAndWrite\x12$.vectordb.VectorEmbedAndWriteRequest\x1a\x1d.vectordb.VectorWriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectordb_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORWRITEREQUEST']._serialized_start=28
  _globals['_VECTORWRITEREQUEST']._serialized_end=77
  _globals['_VECTORBATCHWRITEREQUEST']._serialized_start=79
  _globals['_VECTORBATCHWRITEREQUEST']._serialized_end=151
  _globals['_VECTORWRITERESPONSE']._serialized_start=153
  _globals['_VECTORWRITERESPONSE']._serialized_end=191
  _globals['_VECTORREADREQUEST']._serialized_start=193
  _globals['_VECTORREADREQUEST']._serialized_end=225
  _globals['_VECTORREADRESPONSE']._serialized_start=227
  _globals['_VECTORREADRESPONSE']._serialized_end=278
  _globals['_VECTORUPDATEREQUEST']._serialized_start=280
  _globals['_VECTORUPDATEREQUEST']._serialized_end=330
  _globals['_VECTORUPDATERESPONSE']._serialized_start=332
  _globals['_VECTORUPDATERESPONSE']._serialized_end=371
  _globals['_VECTORDELETEREQUEST']._serialized_start=373
  _globals['_VECTORDELETEREQUEST']._serialized_end=407
  _globals['_VECTORDELETERESPONSE']._serialized_start=409
  _globals['_VECTORDELETERESPONSE']._serialized_end=448
  _globals['_VECTOREMBEDANDWRITEREQUEST']._serialized_start=450
  _globals['_VECTOREMBEDANDWRITEREQUEST']._serialized_end=533
  _globals['_VECTORDB']._serialized_start=536
  _globals['_VECTORDB']._serialized_end=995
# @@protoc_insertion_point(module_scope)
